[default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 0
block_timestamp = 0
cache = true
eth_rpc_url = 'https://a.api.s0.t.hmny.io/'
evm_version = 'london'
ffi = false
force = false
fork_block_number = 21963639
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = []
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['lib']
offline = false
optimizer = true
optimizer_runs = 200
out = 'out'
remappings = [
    'ds-test/=lib/ds-test/src/',
    'solmate/=lib/solmate/src/',
    'weird-erc20/=lib/solmate/lib/weird-erc20/src/',
]
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
src = 'src'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0

